### ISSUE TITLE
依赖了 @typescript-eslint/typescript-estree@2.11.1-alpha.2 但是这个  @typescript-eslint/typescript-estree 没发上去

### ISSUE THREAD

**Issue by RaoHai** [umijs/fabric#17]
Error: [@alipay/bigfish@2.24.1 › @alipay/umi-plugin-bigfish@2.24.1 › @alipay/eslint-config-bigfish@4.1.1 › @umijs/fabric@1.2.4 › @typescript-eslint/parser@2.11.1-alpha.2 › @typescript-eslint/typescript-estree@2.11.1-alpha.2+f9a9fbfc] Can't find package @typescript-eslint/typescript-estree's version: 2.11.1-alpha.2
    at resolve (/opt/taobao/nvm/versions/node/v10.16.0/lib/node_modules/tnpm/node_modules/_npminstall@3.23.0@npminstall/lib/download/npm.js:98:11)
    at resolve.next (<anonymous>)
    at onFulfilled (/opt/taobao/nvm/versions/node/v10.16.0/lib/node_modules/tnpm/node_modules/_co@4.6.0@co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by CharmSun** [comment]
遇到了同样的问题，@typescript-eslint/parser 使用了canary 版本

**Comment by Nabufaces** [comment]
Problem +1

**Comment by chenshuai2144** [comment]
npm 挂了导致的，已经恢复了
今天 npm 的服务出现了不可用的情况，发的包很大的可能被吃掉。比如 lerna 项目一次性发了 10 个包，只有 8 个包发成功了，但另外 2 个包的版本被依赖进了发成功的 8 个包，在 npm 安装这 8 个包的时候就会提示 npm 上没有另外 2 个包的版本。相关 issue，npm 官方现在仍然未回应。
临时解决方案
在 package.json 中增加：
"resolutions": {
  "@typescript-eslint/typescript-estree": "2.11.1-alpha.1"
}
等npm 恢复之后需要删除这个配置，不然可能会造成另外的问题。
2019-12-16 21.19.00
npm 已经恢复。
