### ISSUE TITLE
Failed to load plugin 'unicorn' declared in '.eslintrc.js at /@umijs/fabric/dist/eslint.js'

### ISSUE THREAD

**Issue by lichangchao15442** [umijs/fabric#38]
在使用git cz提交代码时，报下列错误：
```
SyntaxError: Failed to load plugin 'unicorn' declared in '.eslintrc.js » /Users/xxx/node_modules/@umijs/fabric/dist/eslint.js': Invalid regular expression: /(?<before>(?:^|[^\\])(?:\\\\)*)\\(?<data>x[\da-f]{2}|u[\da-f]{4}|u{[\da-f]+})/: Invalid group
at Object.<anonymous> (/Users/xxx/node_modules/eslint-plugin-unicorn/rules/escape-case.js:10:29)
at Module._compile (/Users/xxx/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (/xxx/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
at module.exports (/xxx/node_modules/import-modules/index.js:47:29)
at Object.<anonymous> (/xxx/node_modules/eslint-plugin-unicorn/index.js:6:9)
```
自己已尝试删除依赖并重新安装，但是无果。

**Comment by chenshuai2144** [comment]
这个需要升级 stylelint 的版本

**Comment by hnql** [comment]
Change the `version` in `package.json` file can help to fix it.
