### ISSUE TITLE
"import/no-cycle" is invalid:  Value "∞" should be integer

### ISSUE THREAD

**Issue by leeguooooo** [umijs/fabric#95]
```
yarn run v1.22.10
$ eslint "src/**/*.{ts,tsx,js,jsx}"

Oops! Something went wrong! :(

ESLint: 7.31.0

Error: .eslintrc.js » /Users/zhihu/zhihu.com/fe/ad-taskbiz-web/node_modules/@umijs/fabric/dist/eslint.js » eslint-config-airbnb-base » /Users/zhihu/zhihu.com/fe/ad-taskbiz-web/node_modules/eslint-config-airbnb-base/rules/imports.js:
        Configuration for rule "import/no-cycle" is invalid:
        Value "∞" should be integer.

    at ConfigValidator.validateRuleOptions (/Users/zhihu/zhihu.com/fe/ad-taskbiz-web/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:144:23)
    at /Users/zhihu/zhihu.com/fe/ad-taskbiz-web/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:199:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (/Users/zhihu/zhihu.com/fe/ad-taskbiz-web/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:196:34)
    at ConfigValidator.validateConfigArray (/Users/zhihu/zhihu.com/fe/ad-taskbiz-web/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:322:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/zhihu/zhihu.com/fe/ad-taskbiz-web/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:493:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/zhihu/zhihu.com/fe/ad-taskbiz-web/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:21)
    at FileEnumerator._iterateFilesRecursive (/Users/zhihu/zhihu.com/fe/ad-taskbiz-web/node_modules/eslint/lib/cli-engine/file-enumerator.js:445:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/zhihu/zhihu.com/fe/ad-taskbiz-web/node_modules/eslint/lib/cli-engine/file-enumerator.js:296:49)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by leeguooooo** [comment]
解决了，升级一下 eslint-plugin-import
